#ifndef NATIVEWORDS_H
#define NATIVEWORDS_H

#include "common.h"

WORD_FUNCTION_DECLARATION(number);
WORD_FUNCTION_DECLARATION(dup);
WORD_FUNCTION_DECLARATION(drop);
WORD_FUNCTION_DECLARATION(plus);
WORD_FUNCTION_DECLARATION(minus);
WORD_FUNCTION_DECLARATION(star);
WORD_FUNCTION_DECLARATION(slash);
WORD_FUNCTION_DECLARATION(mod);
WORD_FUNCTION_DECLARATION(dot);
WORD_FUNCTION_DECLARATION(dot_s);
WORD_FUNCTION_DECLARATION(not_in_trie);
WORD_FUNCTION_DECLARATION(colon);
WORD_FUNCTION_DECLARATION(semi_colon);
WORD_FUNCTION_DECLARATION(variable);
WORD_FUNCTION_DECLARATION(array);
WORD_FUNCTION_DECLARATION(exclamation);
WORD_FUNCTION_DECLARATION(if);
WORD_FUNCTION_DECLARATION(then);
WORD_FUNCTION_DECLARATION(else);

#endif
